In [3]:
import tensorflow as tf

In [5]:
arr_constant = tf.constant([[1,2,3],
                            [4,5,6],
                            [6,7,8]], dtype=tf.float64)
arr_constant
# arr_constant.numpy

<tf.Tensor: shape=(3, 3), dtype=float64, numpy=
array([[1., 2., 3.],
       [4., 5., 6.],
       [6., 7., 8.]])>

In [6]:
tf.zeros(shape=[4,5], dtype=tf.float64)

<tf.Tensor: shape=(4, 5), dtype=float64, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])>

In [6]:
tf.fill(dims=[4,5], value=46)

<tf.Tensor: shape=(4, 5), dtype=int32, numpy=
array([[46, 46, 46, 46, 46],
       [46, 46, 46, 46, 46],
       [46, 46, 46, 46, 46],
       [46, 46, 46, 46, 46]])>

In [10]:
tf.random.normal([3,3,4], mean = 14, stddev=14, seed=4)

<tf.Tensor: shape=(3, 3, 4), dtype=float32, numpy=
array([[[ 18.148144  ,  13.560215  ,  13.234052  ,  14.526845  ],
        [ 49.90969   ,   4.907584  ,   4.4166727 ,  20.11633   ],
        [ 34.85717   ,  10.640944  ,  14.697434  ,  19.844782  ]],

       [[ 15.62133   ,  26.293007  ,  17.902782  ,  -8.18907   ],
        [ 30.010952  ,  28.8951    ,  29.82656   ,  32.54684   ],
        [ 43.564323  ,   1.9103842 , -11.785002  ,  20.648914  ]],

       [[  0.13608742,   4.773796  ,   6.531006  ,  25.54206   ],
        [ 29.972486  ,  46.54521   ,  14.6003685 ,  14.240474  ],
        [ 35.24382   ,  11.689147  ,  14.597741  ,  13.026545  ]]],
      dtype=float32)>

In [13]:
import numpy as np

np.around(tf.random.normal([3,3]), 3)
type(np.around(tf.random.normal([3,3]), 3))

numpy.ndarray

In [15]:
listA = [[1,2],[5,7]]

# tf.constant(listA)
tf.convert_to_tensor(listA)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [5, 7]])>

In [17]:
arr_variable = tf.Variable([2,3])
arr_variable

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([2, 3])>

In [20]:
arr_variable = tf.Variable(tf.ones([3,3]))
arr_variable

<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [21]:
arr_variable.assign(tf.zeros([3,3]))

<tf.Variable 'UnreadVariable' shape=(3, 3) dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

slicing

In [35]:
# arr_ran = tf.random.normal([3,3,3])
arr_ran = tf.random.normal([6,6,12,32,64])
arr_ran

<tf.Tensor: shape=(6, 6, 12, 32, 64), dtype=float32, numpy=
array([[[[[ 5.80298007e-01,  1.03204107e+00, -8.68791461e-01, ...,
            7.56575406e-01,  1.60483444e+00, -1.24884856e+00],
          [-1.81135237e-01,  3.86509985e-01,  7.27585375e-01, ...,
            1.67749330e-01,  4.06152755e-01,  2.64999461e+00],
          [ 1.17425907e+00,  6.94003105e-01, -3.45107794e-01, ...,
            3.82437497e-01,  7.75096536e-01, -1.75598371e+00],
          ...,
          [-6.38661325e-01,  2.15489125e+00,  2.45995402e+00, ...,
           -1.16103637e+00, -1.78905439e+00, -6.77813232e-01],
          [-1.26982760e+00,  1.08192372e+00,  9.24475908e-01, ...,
            9.49437559e-01,  3.12660575e-01, -2.42200470e+00],
          [-6.33509636e-01,  1.04747191e-01, -2.47066069e+00, ...,
           -1.29341364e+00,  4.96469766e-01,  6.44442022e-01]],

         [[ 4.74155486e-01,  6.87579215e-01,  3.34547937e-01, ...,
            5.66445649e-01, -7.88205206e-01, -1.02998006e+00],
          [ 1

In [25]:
arr_ran[2,1,2]

<tf.Tensor: shape=(), dtype=float32, numpy=0.27870035>

In [28]:
arr_ran[0:2]

<tf.Tensor: shape=(2, 3, 3), dtype=float32, numpy=
array([[[ 0.80177236,  0.31328034, -1.0765896 ],
        [ 0.08055504, -0.03672693, -0.84390295],
        [-0.15995073,  0.81256783,  0.7417115 ]],

       [[-0.48445523,  1.1626049 ,  1.2802813 ],
        [-0.86598873,  1.1869522 ,  0.33348936],
        [-0.77902377, -2.1721344 , -1.0093076 ]]], dtype=float32)>

indexing

In [30]:
tf.gather(arr_ran, indices=[1,2,0,1,1])

<tf.Tensor: shape=(5, 3, 3), dtype=float32, numpy=
array([[[-0.48445523,  1.1626049 ,  1.2802813 ],
        [-0.86598873,  1.1869522 ,  0.33348936],
        [-0.77902377, -2.1721344 , -1.0093076 ]],

       [[-1.2208816 , -0.16039479,  0.2307037 ],
        [-0.8158718 ,  0.34994218,  0.27870035],
        [-1.5632704 , -0.4583892 , -0.02432075]],

       [[ 0.80177236,  0.31328034, -1.0765896 ],
        [ 0.08055504, -0.03672693, -0.84390295],
        [-0.15995073,  0.81256783,  0.7417115 ]],

       [[-0.48445523,  1.1626049 ,  1.2802813 ],
        [-0.86598873,  1.1869522 ,  0.33348936],
        [-0.77902377, -2.1721344 , -1.0093076 ]],

       [[-0.48445523,  1.1626049 ,  1.2802813 ],
        [-0.86598873,  1.1869522 ,  0.33348936],
        [-0.77902377, -2.1721344 , -1.0093076 ]]], dtype=float32)>

In [32]:
tf.gather_nd(arr_ran, indices=[[0,1],[1,0],[2,2]]).numpy()

array([[ 0.08055504, -0.03672693, -0.84390295],
       [-0.48445523,  1.1626049 ,  1.2802813 ],
       [-1.5632704 , -0.4583892 , -0.02432075]], dtype=float32)

In [33]:
tf.gather_nd(arr_ran, indices=[[0,1,0],[1,0,2],[2,2,0]]).numpy()

array([ 0.08055504,  1.2802813 , -1.5632704 ], dtype=float32)

tensor dimension

In [36]:
# dimension display
arr_ran.shape

TensorShape([6, 6, 12, 32, 64])

In [39]:
#reshaping
print(arr_ran.shape)
arr_ran1 = tf.reshape(arr_ran, [2,2,221184])
print(arr_ran1.shape)

(6, 6, 12, 32, 64)
(2, 2, 221184)


In [41]:
#expension(memperluas)
print(arr_ran.shape)
arr_ran1 = tf.expand_dims(arr_ran,axis=5)
print(arr_ran1.shape)

(6, 6, 12, 32, 64)
(6, 6, 12, 32, 64, 1)


In [44]:
#squeezing(memperkecil)
print(arr_ran1.shape)
arr_ran2 = tf.squeeze(arr_ran1, axis=5)
print(arr_ran2.shape)

(6, 6, 12, 32, 64, 1)
(6, 6, 12, 32, 64)


In [45]:
#transpose(baris jadi kolom)
print(arr_ran.shape)
arr_ran1 = tf.transpose(arr_ran)
print(arr_ran1.shape)

(6, 6, 12, 32, 64)
(64, 32, 12, 6, 6)


In [46]:
#broadcast(array diulang2)
print(arr_ran.shape)
arr_ran1 = tf.broadcast_to(arr_ran, [12,6, 6, 12, 32, 64])
print(arr_ran1.shape)

(6, 6, 12, 32, 64)
(12, 6, 6, 12, 32, 64)


In [47]:
listB= tf.constant([1,2,3,4,5])
tf.broadcast_to(listB, [4,5])

<tf.Tensor: shape=(4, 5), dtype=int32, numpy=
array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])>

tensor statistics collection

In [48]:
arr_ = tf.constant([[19,2,3],
                    [5,13,11],
                    [7,17,1]])

In [51]:
#nilai max

tf.argmax(arr_, axis=1). numpy()

array([0, 1, 1], dtype=int64)

In [52]:
tf.argmin(arr_, axis=0). numpy()

array([1, 0, 2], dtype=int64)

In [54]:
#penjumlahan
tf.reduce_sum(arr_, axis=0).numpy()

array([31, 32, 15])

tensor concatenantion and spliting

In [56]:
#conca
#concat(bergabung)
arr_random1 = tf.random.normal((3,3,3), seed=1)
arr_random2 = tf.random.normal((3,3,3), seed=5)

In [57]:
tf.concat([arr_random1, arr_random2], axis=0)

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[-0.20888524,  0.00542188],
       [ 0.31266254,  0.5998527 ],
       [-1.1780828 , -0.7099414 ],
       [-1.748158  , -0.4953722 ]], dtype=float32)>

In [58]:
arr_random2

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-1.1780828, -0.7099414],
       [-1.748158 , -0.4953722]], dtype=float32)>

In [59]:
#stack(dipisah)
tf.stack([arr_random1, arr_random2], axis=0)

<tf.Tensor: shape=(2, 2, 2), dtype=float32, numpy=
array([[[-0.20888524,  0.00542188],
        [ 0.31266254,  0.5998527 ]],

       [[-1.1780828 , -0.7099414 ],
        [-1.748158  , -0.4953722 ]]], dtype=float32)>

In [63]:
#split
arr_random_1_1= tf.concat([arr_random1, arr_random2], axis=0)

In [64]:
arr_random_1_2= tf.stack([arr_random1, arr_random2], axis=0)

In [66]:
temp= tf.split(arr_random_1_1, num_or_size_splits=4)
temp

[<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[-0.20888524,  0.00542188]], dtype=float32)>,
 <tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[0.31266254, 0.5998527 ]], dtype=float32)>,
 <tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[-1.1780828, -0.7099414]], dtype=float32)>,
 <tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[-1.748158 , -0.4953722]], dtype=float32)>]

In [68]:
temp, temp1, temp2, temp4= tf.split(arr_random_1_1, num_or_size_splits=4)
temp2

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[-1.1780828, -0.7099414]], dtype=float32)>

In [69]:
temp=tf.unstack(arr_random_1_1, axis=1)
temp

[<tf.Tensor: shape=(4,), dtype=float32, numpy=array([-0.20888524,  0.31266254, -1.1780828 , -1.748158  ], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 0.00542188,  0.5998527 , -0.7099414 , -0.4953722 ], dtype=float32)>]

In [70]:
arr_random_1_1.shape

TensorShape([4, 2])